### ISSUE TITLE
error: failed linking references.

### ISSUE THREAD

**Issue by borosuman** [braintree/android-card-form#42] opened 2018-07-24 11:49 UTC
### My configuration:
 compileSdkVersion 28
 minSdkVersion 17
 targetSdkVersion 28
 support Library Version  28.0.0-alpha3
 braintreepayments-card-form version 3.3.0
### Issue description
I am getting AAPT error, 
`error: style attribute 'attr/textColorError (aka in.example.app:attr/textColorError)' not found.
Message{kind=ERROR, text=error: style attribute 'attr/textColorError (aka in.example.app:attr/textColorError)' not found., sources=[/home/ps/.gradle/caches/transforms-1/files-1.1/card-form-3.3.0.aar/0adfda46d436762f0ca3ad472ea91416/res/values/values.xml:55:5-57:13], original message=, tool name=Optional.of(AAPT)}
`
when I try to add the card library in my project.

**Comment by quinnjn** [comment] 2018-07-26 00:15
This is interesting. We don't have the `textColorError` attribute defined in Android Card Form so I'm not to sure why you're getting this issue.

Are you including another one of our repositories like [Drop-in](https://github.com/braintree/braintree-android-drop-in)?

**Comment by borosuman** [comment] 2018-07-27 12:19
Yes. The following dependencies works too. But when I try to use the latest version, its showing the error.
`implementation 'com.braintreepayments:card-form:3.+'
implementation 'com.braintreepayments.api:drop-in:3.+'
implementation 'com.braintreepayments.api:braintree:2.+'`

**Comment by crookedneighbor** [comment] 2018-08-01 13:55
Is there a reason why you're including both the card form and drop-in as dependencies? If you're using Drop-in, why do you need the card form?

**Comment by Viralkanz** [comment] 2018-09-05 13:33
I am only using:
 implementation('com.braintreepayments.api:drop-in:3.5.2') {
        exclude module: 'recyclerview-v7'
        exclude module: 'support-annotations'
        exclude module: 'support-v4'
        exclude module: 'design'
    }

still got the same error. Any help appreciated!

**Comment by quinnjn** [comment] 2018-10-10 00:28
This is a duplicate of [braintree-android-drop-in/issue/77](https://github.com/braintree/braintree-android-drop-in/issues/77). Please follow that issue for updates.

The latest news is we have a published a [snapshot version](https://oss.sonatype.org/content/repositories/snapshots/com/braintreepayments/api/drop-in/3.6.2-SNAPSHOT/) which resolves the issue. We'll publish a release for Drop-in soon.

Closing this issue since it is duplicated in braintree-android-drop-in

**Closed by quinnjn** 2018-10-10 00:28 UTC
